### PR TITLE
Add attacker capabilities to threat model

### PR DESCRIPTION
**Pull request by JanZerebecki**
Add attacker capabilities to threat model

This is adapted from a threat model for operating system software
distributions as part of a higher level plan for securing them from
development to delivery, that I started drafting:
https://gitlab.com/affording-open/distribution

### CODE REVIEW

**Comment by JanZerebecki** [comment]
@david-a-wheeler I'd like to know if this fits with the goals of OpenSSF?

**Comment by david-a-wheeler** [comment]
Hi, I read the full text twice & I don't understand it.

So I'll start with the first two sentences, please help me understand the goal:

> Distribution transparency allows a person to receive a distribution of
> software or data including derivatives and know if anyone shared any
> information of a specific type about it like knowledge of a security
> defect. Thus it affords one to build and deliver an OS securely.

Is the goal to ensure that if anyone worldwide mentions a security defect in a message,
even if that message is private & encrypted, that this message would
automatically be decrypted & revealed to an unconnected third party?
I don't see how that's possible, and in any case it seems obviously undesirable.
"Anyone shared any information" is really broad.

Is this a guarantee that if information is distributed in a certain way,
a certain set of parties are *guaranteed* to receive it?
That's challenging too. E.g., you're guaranteed to have received certain
information?

Sorry, I really don't understand this proposal.

**Comment by JanZerebecki** [comment]
Sorry for being imprecise. My question was meant about the addition in this commit, not the linked context where I originally thought it up. I started with the attacker capabilities of the threat model to understand if this WG and I can use shared language for what parts any solution solves. I'm interested in putting the rest from the Google doc in here and polishing it.

---

That is good and welcome feedback for my linked draft. You correctly picked up on the most difficult part, the transparency log, which it only assumes. Thank you, this is exactly the ability for critical analysis that this space needs.

Trillian, as known for implementing Certificate Transparency and being used for sigstore, has multiple failure modes that it doesn't currently detect or protect against. One of these is split-view, where Bob gets different answers from a malicious Trillian service for the same question compared to Alice. Another is availability as Trillian installations are expected to fail. I'm interested in the protocol dealing with these to support analyzing its effect and not punting it to the end user. I haven't yet found any satisfying solution in academic writing or in practical implementation, but I am only at the beginning of reading up and haven't even published my current notes. Do you know of one?

AFAIK it is possible to guarantee in a protocol that you either get the same answer as everyone else who also gets an answer who is a cooperating participant as long as there is at least one besides you or know when you failed. But, it is difficult to twist that guarantee into something practically useful.

My current hunch is to use an easier transport with less guarantees than a transparency log, like a peer to peer content addressable sync based on signature, and later get back to it. Solving the things on top of an transport has probably more effect per effort than a transparency log.

With a transparency log assumed, the link lists things one would want to secure with this to build and deliver an OS, many of which are currently not widely done but have known practical solutions. E.g. mirror git sources in a way that don't overwrite history, automatically verify SLSA with reproducible builds, etc. A less known one from it is probably to coordinate security review with a web of trust. One project set out to solve that is https://github.com/crev-dev/cargo-crev , but before that becomes widely usable it needs to be able to correct semantic drift of the machine readable assertions and better scale trust.

Does that answer your questions?

---

While it might be useful to know which other things from the link we can cooperate on, back to my question: Can we cooperate on the threat model?

**Comment by david-a-wheeler** [comment]
OpenSSF is about *security* broadly. There's no single threat model AFAIK, since different situations have different threat models.

**Comment by david-a-wheeler** [comment]
Not at all! I'm just saying that the OpenSSF has not formally blessed any specific threat model as the "one true threat model". Different OpenSSF projects are focused on different threat models.

**Comment by JanZerebecki** [comment]
@kimsterv continuing from the discussion in the meeting:
Do you think it is in scope for SLSA to enumerate and explain every supply chain threat resulting from the here proposed attacker capabilities in its threats chapter (even when solving it is out of scope for SLSA)?
Then do the here proposed attacker capabilities fit in that chapter?

**Comment by JanZerebecki** [comment]
Yes, that paper is helpful. It also has some good references. But I guess we can't just adopt it as is, though it is probably a good idea to compare our taxonomy.

My current blocker here is whether SLSA considers the level of defense in scope, that my suggested attacker capabilities would require. And if not, if SLSA is willing to mention even the possibility of end-to-end considerations. And if not, if this working group is.

**Comment by melba-lopez** [comment]
closing due to being old/inactive.  If needed in the future, will create a new PR.

**Comment by JanZerebecki** [comment]
@melba-lopez Please reopen this. The questions are not answered.

**Comment by melba-lopez** [comment]
@hepwori @camaleon2016 @david-a-wheeler this appears to be in scope for SLSA or the End User's WG (AE/AF - in diagram below) but not this WG.  

https://openssf.org/wp-content/uploads/sites/132/2023/04/OpenSSF_CICD.pdf

**Pull request closed without merging**
